# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets', 'assets'),
    ],
    hiddenimports=[
        'database_manager',
        'library_manager',
        'audio_engine',
        'config_manager',
        'lyrics_manager',
        'lyrics_translator',
        'letras_provider',
        'online_stream_manager',
        'mpris_server',
        'win_media_client',
        'ui.music_home_view',
        'ui.expanded_view',
        'ui.image_cache',
        'ui.context_menus',
        'ui.player_widget',
        'ui.small_playlist',
        'ui.unified_mode_menu',
        'ui.icon_manager',
        'ui.personalization_dialog',
        'ui.add_link_dialog',
        'ui.font_manager',
        'ui.lyrics_view_widget',
        'ui.styles',
        'ui.color_extractor',
        'ui.marquee_label',
        'ui.y2k_volume_slider',
        'tinytag',
        'mutagen',
        'sqlite3',
        'requests',
        'PIL',
        'yt_dlp',
        'winsdk.windows.media',
        'winsdk.windows.storage',
        'winsdk.windows.storage.streams',
        'winsdk.windows.foundation',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='CustomMusicPlayer',
    icon='assets/icon.ico',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
