# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'database_manager',
        'library_manager',
        'audio_engine',
        'config_manager',
        'mpris_server',
        'win_media_client',
        'ui.music_home_view',
        'ui.expanded_view',
        'ui.player_widget',
        'ui.small_playlist',
        'ui.unified_mode_menu',
        'ui.personalization_dialog',
        'ui.styles',
        'ui.color_extractor',
        'ui.marquee_label',
        'ui.equalizer_widget',
        'ui.y2k_volume_slider',
        'ui.gradient_dialog',
        'tinytag',
        'mutagen',
        'sqlite3',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='CustomMusicPlayer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
